name = "Polynomials4ML"
uuid = "03c4bcba-a943-47e9-bfa1-b1661fc2974f"
authors = ["Christoph Ortner <christophortner@gmail.com> and contributors"]
version = "0.2.2"

[deps]
ACEbase = "14bae519-eb20-449c-a949-9c58ed33163e"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
ObjectPools = "658cac36-ff0f-48ad-967c-110375d98c9d"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ACEbase = "0.4.2"
Adapt = "3.5"
BenchmarkTools = "1"
ChainRulesCore = "1"
Combinatorics = "1"
ForwardDiff = "0.10"
HyperDualNumbers = "4.0.10"
LoopVectorization = "0.12"
LuxCore = "0.1.3"
NamedTupleTools = "0.14.3"
ObjectPools = "0.3.1"
QuadGK = "2"
SpecialFunctions = "2.2"
StaticArrays = "1.5"
StrideArrays = "0.1.25"
julia = "1.8"

[extras]
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Lux", "Printf", "Zygote", "Optimisers"]
