name = "Polynomials4ML"
uuid = "03c4bcba-a943-47e9-bfa1-b1661fc2974f"
authors = ["Christoph Ortner <christophortner@gmail.com> and contributors"]
version = "0.5.7"

[deps]
ACEbase = "14bae519-eb20-449c-a949-9c58ed33163e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SpheriCart = "5caf2b29-02d9-47a3-9434-5931c85ba645"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WithAlloc = "fb1aa66a-603c-4c1d-9bc4-66947c7b08dd"

[compat]
ACEbase = "0.4.5"
BenchmarkTools = "1"
Bumper = "0.7.0"
ChainRulesCore = "1"
Combinatorics = "1"
DiffResults = "1.1.0"
ForwardDiff = "0.10, 1.0"
GPUArraysCore = "0.2.0"
HyperDualNumbers = "4.0.10"
Interpolations = "0.16.2"
KernelAbstractions = "0.9.34"
LinearAlgebra = "1.10"
LuxCore = "1.2.0"
QuadGK = "2"
Random = "1.10"
SparseArrays = "1.10"
SpecialFunctions = "2.2"
SpheriCart = "0.2.3"
StaticArrays = "1.5"
Test = "1.10"
WithAlloc = "0.1.0"
julia = "1.10"

[extras]
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Printf", "Optimisers", "Zygote"]
